services:
  frontend:
    build:
      context: frontend/ 
    ports: [80:80]

  broker-service:
    build:
      dockerfile: services.Dockerfile
      context: .
    command: /app/broker-service
    ports: [8080:8080]
