configuration:
  ports:
    web: 8080

types:
  stringVar: hello world
  intVar: 101
  boolVar: true
  listIntVar: [1,2,3,4]
  listStringVar: ["a", "b", "c"]

postgres:
  queries:
    GetUserById: SELECT id,name,age,married FROM Demo WHERE id = $1
    CreateUser: INSERT INTO Demo(name,age,married) VALUES($1, $2, $3)
    GetAllUsers: SELECT * FROM Demo